Module7 task2
htmlacademy-php3/94214-what-to-watch-2 pull request #13
Opened 2023-05-14 14:19 UTC by sokoloff-rv

2023-05-14 17:59 UTC, dmekhov requested changes

2023-05-14 17:59 UTC, dmekhov commented on app/Http/Controllers/FilmController.php
> +            CreateFilmJob::dispatch($data);
И ты тут по сути не исправил предыдущее замечание.  

Основная идея на самом деле такая:
Фильм в очереди может простоять долгое время, если много запросов.  
Поэтому нужно сначала поставить фильму статус pending, и создать задачу.  
Что будет если очередь занята и в этот момент отправить несколько раз запрос на создание фильма с одинаковым imdb_id? (ошибки валидации не будет)

2023-05-14 17:59 UTC, dmekhov commented on app/Jobs/CreateFilmJob.php
> +            $movieData['status'] = $status;
Ты тут назначаешь статус  и строчкой ниже в createFromData заменяешь его на STATUS_MODERATE

2023-05-14 17:59 UTC, dmekhov commented on tests/Unit/FilmJobTest.php
> +            'imdb_id' => $imdbId,
Добавь тут проверку изменения статуса ;)

2023-05-14 17:59 UTC, dmekhov commented on tests/Feature/FilmControllerTest.php
> +                'status' => Film::STATUS_PENDING,
И при выполнении этого запроса (до запуска очереди) в БД должен появиться фильм с 
```
'imdb_id' => $imdbId,
'status' => Film::STATUS_PENDING,
```
;)

2023-05-14 17:59 UTC, dmekhov commented on tests/Unit/FilmJobTest.php
> +        Mockery::close();
Вообще не обязательно вызывать Mockery::close();

Он и так вызывается в tearDown методе базового класса TestCase лары

2023-05-14 17:59 UTC, dmekhov commented on app/Services/FilmService.php
> +    public function __construct(ActorService $actorService, GenreService $genreService)
А ты знаешь что можно так конструктор объявить?

```
public function __construct(private ActorService $actorService, private GenreService $genreService)
{
}
```

и тогда не надо будет в конструкторе назначать свойства, и в классе выше объявлять их

(кстати, если ты не планируешь переопределять свойства в классах наследниках - лучше делать их приватными. таким образом ты подсказываешь другим разработчикам - что эти переменные можно безболезненно менять внутри класса. если же я вижу preotected/public методы или свойства - я вынужден внимательно искать не сломается ли что-то от моих изменений)

2023-05-14 17:59 UTC, dmekhov commented on app/Http/Responses/SuccessPaginationResponse.php
> +        return [
А просто `return $this->prepareData();` нельзя сделать? ты ведь тут присваиваешь все поля как есть массиву

2023-05-14 17:59 UTC, dmekhov commented on app/Models/Film.php
> +            return $this->favoritedByUsers()->where('user_id', $user->id)->exists();
setIsFavoriteAttribute - теперь ведь не нужен?

2023-05-14 17:59 UTC, dmekhov commented on app/DTO/FilmData.php
> +    public ?string $poster_image;
Ты можешь задать значение по умолчанию null, и тогда тебе не придется передавать не обязательные поля при инициализации.

И по идее неплохо бы создавать класс через конструктор - передавая туда обязательные поля, иначе получается что я не могу вызвать класс так:

```
$filmData = new FilmData();
$filmData->toArray();
```

окажется что я еще должен назначить какие-то поля

2023-05-14 17:59 UTC, dmekhov commented on app/Http/Controllers/FilmController.php
> +    public function store(StoreFilmRequest $request, FilmService $filmService)
filmService - ты тут не используешь

2023-05-14 17:59 UTC, dmekhov commented on tests/Feature/FilmControllerTest.php
> +        $movieService = Mockery::mock(MovieService::class);
До вызова MovieService тут не доходит - поэтому можно его не моккать

2023-05-14 17:59 UTC, dmekhov commented on tests/Feature/FilmControllerTest.php
> +        $mockMovieService = Mockery::mock(MovieService::class);
До вызова MovieService тут не доходит - поэтому можно его не моккать, как и в других тестах с ошибками 

А если ты боишься случайно отправить запрос к внешнему сервису из тестов - это решается тем что ссылка на внешний сервис должна храниться в конфиге, определяться в env, и переопределяться в phpunit.xml

2023-05-15 14:45 UTC, sokoloff-rv commented on app/Jobs/CreateFilmJob.php
> +            $movieData['status'] = $status;
Ну по ТЗ так ) Я просто не понял, что подразумевается сохранение фильма в базе. Теперь логика стала понятна )

> В момент создания заявки, фильм сохраняется только с imdb_id и статусом «в ожидании» (pending). После загрузки данных, статус меняется на «на модерации» (moderate).

2023-05-15 15:17 UTC, sokoloff-rv commented on app/Services/FilmService.php
> +    public function __construct(ActorService $actorService, GenreService $genreService)
Да, знаю, я так даже делал в этом проекте где-то. Просто не всегда пока ещё вспоминаю про это ) Про приватные свойства понял, учту на будущее. Полезная логика.

2023-05-15 15:21 UTC, sokoloff-rv commented on app/Http/Responses/SuccessPaginationResponse.php
> +        return [
Можно, но тогда формат ответа будет не совсем как по ТЗ. Я это делал, чтобы было строгое следование ожидаемому формату ответа, даже порядок выставлен соответствующий )

> В случае запроса списка с постраничным выводом так же на верхнем уровне выводится информация о к-ве элементов всего, к-ве элементов на страницу, ссылки на предыдущую страницу и следующую
> 
> ```
> {
>   "data": [
>     {
>       "id": 1,
>       "name": "The Grand Budapest Hotel",
>       "preview_image": "img/the-grand-budapest-hotel.jpg"
>     },
>     {
>       "id": 2,
>       "name": "The Film",
>       "preview_image": "img/the-film.jpg"
>     }
>   ],
>   "current_page": 1,
>   "first_page_url": "http://example.com/api/films?page=1",
>   "next_page_url": null,
>   "prev_page_url": null,
>   "per_page": 6,
>   "total": 2  
> }
> ```

2023-05-15 15:30 UTC, sokoloff-rv commented on app/Models/Film.php
> +            return $this->favoritedByUsers()->where('user_id', $user->id)->exists();
Точно, не нужен, у меня это теперь через модель юзера делается, удаляю.

2023-05-15 15:36 UTC, sokoloff-rv commented on tests/Unit/FilmJobTest.php
> +        Mockery::close();
Не заглядывал туда, не знал, что он вызывается и так ) Где-то просто попадалось, что это хороший тон прописывать после использования моков Mockery::close();. 
Убрал везде, раз в этом нет смысла 👌

2023-05-15 15:58 UTC, sokoloff-rv commented on tests/Feature/FilmControllerTest.php
> +        $mockMovieService = Mockery::mock(MovieService::class);
Я не боюсь, просто то ли в ТЗ, то ли в критериях прописано, что во время теста не должно быть обращений к реальным сервисам, все должно быть замокано. Поэтому везде, где идет обращение к роуту, я добавил моки. От греха подальше ) Я понимаю, что везде, где ожидаются ошибки, до реального обращения к внешнему сервису дело не дойдет, так как там на подлете ещё отлуп придет.
У меня просто на прошлых проектах проверяющие наставники иногда чудили, поэтому я тут моки прописал сразу, чтобы не было ко мне вопросов )

2023-05-15 16:02 UTC, dmekhov commented on tests/Feature/FilmControllerTest.php
> +        $mockMovieService = Mockery::mock(MovieService::class);
Не должно быть обращений - это верно.   
Но и лишнего кода тоже не должно быть ;)   
Если у тебя ошибка выбрасывается не заходя в контроллер, то до сервиса дело не должно доходить, и его незачем моккать ;)  
Но ты можешь в этом убедиться задав несуществующий адрес внешнему сервису - и словив ошибку, в случае если до сервиса все же дошла очередь **почему-то**

2023-05-15 16:02 UTC, sokoloff-rv commented on tests/Feature/FilmControllerTest.php
> +        $movieService = Mockery::mock(MovieService::class);
Я понимаю, что не доходит. Если ожидается ошибка, то ещё на подлете приходит отлуп. Просто то ли в ТЗ, то ли в критериях, есть требование, что в тестах обращения к реальным сервисам должны быть замоканы. Поэтому везде, где в тестах встречается обращение к роуту, я добавил моки. Чтобы не было ко мне вопросов ) А то у меня проверяющие наставники уже чудили на прошлых проектах.

2023-05-15 16:06 UTC, sokoloff-rv commented on tests/Feature/FilmControllerTest.php
> +        $mockMovieService = Mockery::mock(MovieService::class);
Про лишний код понял, убираю )

2023-05-15 18:47 UTC, dmekhov commented on app/Http/Responses/SuccessPaginationResponse.php
> +        return [
Ты имеешь ввиду что дефолтный пагинатор больше полей отдает?

В этом случае тебе может помочь https://laravel.com/docs/10.x/helpers#method-array-only  
А вообще, я бы лично не придрался к такому в данном случае, именно потому что те поля которые отдает дефолтный пагинатор - они в целом не лишние, а нужное есть

(менять не нужно)

2023-05-15 19:03 UTC, dmekhov approved these changes

2023-05-15 19:03 UTC, dmekhov commented on app/Services/FilmService.php
> +    public function createFromData(array $data): Film
Ты вроде не используешь этот метод

2023-05-15 19:03 UTC, dmekhov commented on app/Services/FilmService.php
> +        if ($film) {
Ты предполагаешь что фильма может не быть, и этом возвращаешь `$film` по итогу, при этом в сигнатуре метода возвращаемый тип - модель `Film`, не `null`

2023-05-15 19:03 UTC, dmekhov commented on app/Services/FilmService.php
> +        $film->status = Film::STATUS_MODERATE;
Если быть честным, это не ответственность сервиса. Ведь твой метод именно сохраняет фильм с переданными данными, и он ничего про твои бизнес процессы не знает.

Статус должен либо передаваться отдельным параметром функции, либо в составе $data

(я не буду считать это замечанием, т.к. это не про домашку, но если бы это был реальный проект - я бы отправил на доработку такую задачу, поэтому рекомендую все же в последствии переделать)

2023-05-15 19:03 UTC, dmekhov commented on tests/Unit/FilmJobTest.php
> +        Film::create($data);
Вообще лучше для этого использовать фабрику, при вызове фабрики не срабатывают никакие события, обсерверы и прочая подкапотная логика.

При создании объекта через модель может оказаться что у тебя переопределен метод модели, или есть какие-то setter методы, или реакция на события, или еще множество или

2023-05-15 19:03 UTC, merged

2023-05-16 08:01 UTC, sokoloff-rv commented on app/Services/FilmService.php
> +    public function createFromData(array $data): Film
Да, не использую. Но так как он уже был готов, то решил оставить, вдруг пригодится. Всё-таки это сервис, не модель, тут вроде бы неиспользуемые возможности не возбраняются. Или лучше так не делать?

2023-05-16 08:57 UTC, sokoloff-rv commented on app/Services/FilmService.php
> +        if ($film) {
Точно, исправил. Заодно и логику добавления нового фильма поправил. А то получалось, что если был отправлен валидный IMDB ID, но от несуществующего ещё фильма, то пустой фильм (только со статусом и айдишником) продолжал висеть в базе после выполнения задачи.

2023-05-16 08:57 UTC, sokoloff-rv commented on tests/Unit/FilmJobTest.php
> +        Film::create($data);
Исправил.

2023-05-16 08:58 UTC, sokoloff-rv commented on app/Services/FilmService.php
> +        $film->status = Film::STATUS_MODERATE;
Вынес статус в отдельный параметр, так мне кажется логичнее 👌