Проект подготовлен к защите
htmlacademy-php3/94214-what-to-watch-2 pull request #16
Opened 2023-05-26 09:16 UTC by sokoloff-rv

2023-05-26 20:35 UTC, dmekhov requested changes
Хороший результат.  
Есть что улучшать, но всегда есть что улучшать ;)
Основные комментарии о том как сделать код аккуратнее, чище, и более поддерживаемым. 

Я оставил пару замечаний которые нужно исправить для выполнения ТЗ и критериев - [Исправить].  

Кроме того есть ряд комментариев помеченных как [Рекомендация] - это рекомендации на которые стоит обратить внимание и исправить позже, или придерживаться такого подхода в будущих проектах. Но они не влияют на получение оценки, т.к. не описаны в требованиях.  
А также [Подсказка] - это несколько подсказок о том как можно иначе (чуть аккуратнее) описать тот же код.

Если будут нужны какие-то пояснения по оставленным комментариям - пиши обсудим.

2023-05-26 20:35 UTC, dmekhov commented on app/Console/Kernel.php
>          // $schedule->command('inspire')->hourly();
[Исправить]

Закомменченный пример кода из стандартной подставки - лучше убрать

(Это больше про стили, но можно к Б8 притянуть)

2023-05-26 20:35 UTC, dmekhov commented on app/Http/Controllers/AuthController.php
> +                abort(Response::HTTP_UNAUTHORIZED, trans('auth.failed'));
[Исправить]

Ты выбрасываешь тут исключение, а потом на 34 строке его ловишь  

В итоге переданный код ответа не передается в FailResponse

Это лучше исправить (**п.5 ТЗ**) - простое решение - прямо тут вернуть ответ ошибки с нужным кодом
хорошее решение - в catch методе проанализировать код ошибки исключения и подставить в ответ (но как это правильнее сделать опишу отдельно, для формального решения задачи - можно пойти "простым" путем)

2023-05-26 20:35 UTC, dmekhov commented on app/Http/Controllers/AuthController.php
> +        } catch (\Exception $e) {
[Рекомендация]

Описанный выше коммент, про abort - хороший пример почему try catch в каждом методе это не очень хорошо.  
(не говоря о том что у тебя куча копипасты try-catch)  
По хорошему - у тебя есть единая точка выхода ExceptionHandler в которой ты можешь отлавливать и оборачивать все ошибки. Ты уже это делаешь для некоторых ошибок (ошибка 404, ошибка валидации).  

Смотри, по цепочке - в базовом методе `\Illuminate\Foundation\Exceptions\Handler::render()` есть вызов метода `renderExceptionResponse` а там дальше `prepareJsonResponse` который возвращает JsonResponse, вот его-то ты и можешь переопределить, вернув свой `FailResponse`, в котором получить сообщение и код ответа из исключения.

2023-05-26 20:35 UTC, dmekhov commented on app/Http/Controllers/CommentController.php
> +                'user_id' => $user->id,
[Подсказка]

Если ты больше не переиспользуешь переменную $user ее можно отдельно не заводить а сразу тут указать `Auth::id()`

2023-05-26 20:35 UTC, dmekhov commented on app/Http/Requests/CommentRequest.php
> +        return [
[Исправить]

Тут по идее не хватает валидации указателя на родительский коммент.  
Он может быть nullable, но если передан - нужно убедиться что передан существующий  
https://laravel.com/docs/10.x/validation#rule-exists

2023-05-26 20:35 UTC, dmekhov commented on app/Http/Controllers/CommentController.php
> +            if ($comment->children()->count() > 0) {
[Подсказка]

В целом тут не обязательно делать эту проверку, запрос к БД будет (условно) `удали все комменты у которых такой родитель` если таких комментов нет - ну и ладно.

2023-05-26 20:35 UTC, dmekhov commented on app/Http/Controllers/FavoriteController.php
> +            if ($user->favoriteFilms()->where('film_id', $film->id)->exists()) {
[Рекомендация]

Ты в нескольких местах используешь этот код, можно перенести его в метод модели пользователя, какой нибудь `$user->hasFavorite($film->id)` ;)

2023-05-26 20:35 UTC, dmekhov commented on app/Http/Controllers/FilmController.php
> +            $pageQuantity = 8;
[Рекомендация]

Лучше избегать таких констант в коде (особенно если ты потом где-то, например в тестах тоже применяешь эти значения), а выносить их в конфиг.

2023-05-26 20:35 UTC, dmekhov commented on app/Http/Controllers/FilmController.php
> +            $films = Film::query()
[Рекомендация]

В списках (список фильмов, список избранного, и пр - т.е. там где тебе не нужны все параметры сущности) лучше ограничивать перечень возвращаемых параметров, возвращая только то что нужно для отображения в списке. Особенно это актуально для всяких статей, когда текст статьи может быть довольно большим, но и в нашем случае - описание фильма тоже присутствтует.

2023-05-26 20:35 UTC, dmekhov commented on app/Http/Controllers/FilmController.php
> +                    return $query->whereHas('genres', function ($query) use ($genre) {
[Подсказка]

Можно чуть короче `$query->whereRelation('genres', 'name', $genre);`

2023-05-26 20:35 UTC, dmekhov commented on app/Models/Film.php
> +    public function calculateRating()
[Исправить]

Забыл вызывать этот метод, при добавлении оценок (добавлении комментариев)

2023-05-26 20:35 UTC, dmekhov commented on app/Http/Controllers/UserController.php
> +                    Storage::delete($oldAvatar);
[Рекомендация]

Я бы удалял старый аватар после сохранения нового и обновления модели пользователя, на случай ошибок ;)

2023-05-26 20:35 UTC, dmekhov commented on app/Http/Responses/FailResponse.php
> +        if ($exception) {
[Подсказка]

Если разделить класс на два (как с ответом пагинации) - код можно будет сделать чуть аккуратнее ;)

2023-05-26 20:35 UTC, dmekhov commented on app/Services/MovieService/MovieService.php
> +class MovieService
[Рекомендация]

Если у тебя сервис не содержит никакой логики а только дергает репозиторий - то ты можешь дергать репозиторий и без сервиса ;)

2023-05-26 20:35 UTC, dmekhov commented on app/Jobs/UpdateCommentsForAllFilmJob.php
> +        $response = Http::get('http://guide.phpdemo.ru/api/comments', $params);
[Рекомендация]

Я бы для получения комментов тоже в репозиторий логику вынес.  
И источник может поменяться, и что бы прямо в джобе логики этой не было.

(формально это не ошибка, потому что про это нет ни в ТЗ, ни в критериях, ни в домашке. а домашка про реепозитории была про фильмы. но все же, рекомендацию - оставлю ;))

2023-05-26 20:35 UTC, dmekhov commented on app/Services/MovieService/MovieAcademyRepository.php
> +    private string $baseUrl = 'http://guide.phpdemo.ru/api/films/';
[Рекомендация]

Лучше хранить это в конфиге.

2023-05-26 20:35 UTC, dmekhov commented on app/Jobs/UpdateCommentsForAllFilmJob.php
> +            $newComments = $response->json();
[Подсказка]

Если использовать метод `->collect()` ответ будет возвращен в виде коллекции, а не массива, и с ним будет проще взаимодействовать, фильтровать, получать список id и пр ;)

2023-05-26 20:35 UTC, dmekhov commented on app/Services/MovieService/MovieAcademyRepository.php
> +        $cachingTime = 60;
[Рекомендация]

Лучше хранить это в конфиге. И управлять через env.

2023-05-26 20:35 UTC, dmekhov commented on app/Services/MovieService/MovieAcademyRepository.php
> +        Cache::put($cacheKey, $data, 60 * 60);
[Рекомендация]

Третий параметр может быть передан в виде Carbon объекта (например `now()->addHour()`), до когда закешировать, это удобнее потому что будет сразу понятно на сколько кешируется ответ. В отличие от условных `60`, когда сразу не понятно на минуту или на час это кешироование.

2023-05-26 20:35 UTC, dmekhov commented on routes/api.php
> +Route::post('/register', [RegisterController::class, 'register']);
[Рекомендация]

Если давать роутам имена `->name('auth.register')` то в тестах можно будет обращаться к ним по имени, не думая о том какой там у него путь, префиксы и пр, и не меняя тест, если в процессе путь изменится.

2023-05-27 19:31 UTC, sokoloff-rv commented on app/Http/Controllers/AuthController.php
> +        } catch (\Exception $e) {
Идею понял, но реализовать пока не получилось. Видимо где-то не до конца понимаю механизм, на следующей неделе вернусь к этому моменту. Пока в методе login() реализовал возврат нужного кода ответа по-простому, чтобы закрыть критерий )

2023-05-27 19:39 UTC, sokoloff-rv commented on app/Services/MovieService/MovieService.php
> +class MovieService
Это я уже тоже понял под конец проекта ) Впрочем, этот сервис вырос из домашки про репозитории и внедрение зависимостей, так что пусть уже остается. Но на будущее я учту этот момент.

2023-05-28 09:48 UTC, dmekhov commented on app/Console/Kernel.php
>          // $schedule->command('inspire')->hourly();
Принято

2023-05-28 09:48 UTC, dmekhov commented on app/Http/Controllers/AuthController.php
> +                abort(Response::HTTP_UNAUTHORIZED, trans('auth.failed'));
Принято

2023-05-28 09:49 UTC, dmekhov commented on app/Http/Requests/CommentRequest.php
> +        return [
Принято

2023-05-28 09:55 UTC, dmekhov approved these changes

2023-05-28 09:55 UTC, dmekhov commented on config/services.php
> +        'base_url' => env('ACADEMY_BASE_URL'),
[рекомендация]

Когда заводишь новые env переменные - добавляй их в .env.example (если они содержат секретные данные - пароли, ключи - в значение пиши заглушку "password", "secret" или вроде того.

Иначе при развертывании другим разработчиком он столкнется с неожиданной ошибкой, и может даже не сразу.

2023-05-28 09:55 UTC, dmekhov commented on tests/Feature/FilmControllerTest.php
> +            $film->genres()->attach($genre);
[Рекомендация]

Почитай про создание моделей сразу со связями. https://laravel.com/docs/10.x/eloquent-factories#pivot-table-attributes

`Film::factory($count)->hasAttached($genre)->create();`  

Чуть удобнее и аккуратнее ;)

Этот же способ можно использовать и в сидах, что бы сразу создать нужный набор даннных

2023-08-14 08:18 UTC, closed without merging