Module4 task2
htmlacademy-php3/94214-what-to-watch-2 pull request #7
Opened 2023-04-25 17:19 UTC by sokoloff-rv

2023-04-26 17:28 UTC, dmekhov requested changes

2023-04-26 17:28 UTC, dmekhov commented on app/Models/Film.php
> +{
Связь с комментами, для получения всех комментариев фильма - тут не помешала бы ;)

2023-04-26 17:28 UTC, dmekhov commented on database/factories/UserFactory.php
> +            'role' => 'user',
В момент когда ты где-то указываешь захардкоженную строку в качестве значения, обычно стоит задуматься все ли идет по плану.

А какие еще могут быть роли? А где это указано?  

Пока можем отложить это до домашки про роли. Но нужно будет не забыть поправить это здесь (и в миграции ;)).

2023-04-26 17:28 UTC, dmekhov commented on database/factories/CommentFactory.php
> +            'user_id' => $this->faker->numberBetween(1, 5),
Ты тут ссылаешься на пользователя которого еще нет. Что будет если вызвать эту фабрику до вызова фабрики создания пользователя?

В дальнейшем ты будешь вызывать фабрики в тестах, и там далеко не всегда будут нужны все 5 пользователей. 

Для решения этой проблемы ты можешь предоставить ларе возможность выбрать существующего (или создать) пользователя указав `User::factory()` в качестве значения (так же и с остальными)

2023-04-26 17:28 UTC, dmekhov commented on database/seeders/ActorFilmSeeder.php
> +        $films->each(function (Film $film) use ($actors) {
Эти сидеры пока не проверяю - если их тебе хватает для проверки - ок  
о том как это будет лучше сделать - будет в разделе про тесты и фабрики

2023-04-26 17:28 UTC, dmekhov commented on app/Http/Controllers/FilmController.php
> +        $film = Film::find($id);
Почитай про https://laravel.com/docs/10.x/routing#route-model-binding и используй везде где есть такая возможность.

2023-04-26 17:28 UTC, dmekhov commented on app/Http/Controllers/FilmController.php
> +            return new SuccessResponse($film);
Ты пытаешься вернуть успешный ответ?

там действительно может быть ошибка?

а до этого ошибки быть не может (при обращении к модели фильмов, например)?

2023-04-26 17:28 UTC, dmekhov commented on app/Http/Controllers/FilmController.php
> +            return new SuccessResponse($films);
Там по идее ответ с пагинацией должен быть  

(Но можем это отложить на доработки, туда же и фильтрация и пр)

2023-04-26 17:28 UTC, dmekhov commented on app/Http/Controllers/CommentController.php
> +            $comments = Comment::where('film_id', '=', $filmId)->get();
А что если такого фильма нет?

Если тут использовать route model binding - то комменты можно будет получать через связь.

2023-04-26 17:38 UTC, sokoloff-rv commented on app/Models/Film.php
> +{
Зачем? Если я получаю все комментарии к фильму в контроллере комментариев?

2023-04-26 17:39 UTC, sokoloff-rv commented on database/factories/UserFactory.php
> +            'role' => 'user',
Не понял про захардкоженную строку в качестве значения.

2023-04-26 17:45 UTC, sokoloff-rv commented on app/Http/Controllers/FilmController.php
> +            return new SuccessResponse($films);
Я боюсь такими темпами не успею добраться до доработок проекта )

2023-04-27 04:51 UTC, sokoloff-rv commented on app/Models/Film.php
> +{
В общем не понял зачем это (учитывая, что комментарии к фильму я получаю в другом месте), но сделал.

2023-04-27 05:22 UTC, sokoloff-rv commented on database/factories/UserFactory.php
> +            'role' => 'user',
Если речь о том, что передается голая строка 'user', то это потому что пока мне нужны были только пользователи с этой ролью и я не стал заморачиваться. Вынесу в константы класса User.

2023-04-27 05:49 UTC, sokoloff-rv commented on app/Http/Controllers/CommentController.php
> +            $comments = Comment::where('film_id', '=', $filmId)->get();
Поправил. Хотя по-прежнему не очень понимаю почему нужно делать именно так. Пока что выглядит так, как будто это просто ещё один способ реализации. Какие преимущества дает - не ясно.

2023-04-27 05:55 UTC, sokoloff-rv commented on app/Http/Controllers/FilmController.php
> +        $film = Film::find($id);
Разобрался, поправил.

2023-04-27 05:56 UTC, sokoloff-rv commented on database/factories/CommentFactory.php
> +            'user_id' => $this->faker->numberBetween(1, 5),
Исправил.

2023-04-27 05:59 UTC, sokoloff-rv commented on app/Http/Controllers/FilmController.php
> +            return new SuccessResponse($film);
Да, мой косяк. Надо было всю логику заворачивать в try. Сейчас метод уже изменился, но ошибку увидел.

2023-04-27 06:02 UTC, sokoloff-rv commented on app/Http/Controllers/FilmController.php
> +            return new SuccessResponse($films);
Разобрался с пагинацией, добавил.

2023-04-27 07:53 UTC, dmekhov commented on app/Http/Controllers/CommentController.php
> +            $comments = Comment::where('film_id', '=', $filmId)->get();
> Хотя по-прежнему не очень понимаю почему нужно делать именно так.

Тебе нужно либо самому руками проверять есть ли такой фильм в базе (перед тем как искать комменты для него), и отдавать ошибку если нет  
И потом получать комменты по film_id как у тебя было

Либо сразу получить модель фильма (и проверку отдать на откуп фреймворка) и тут уже одной строкой вернуть комменты фильма

Конечно почти любую задачу можно решить больше чем одним способом, но использование route model binding снимает с тебя часть ответственности и позволяет не реализоваывать то что уже есть в фреймворке

Что касается использования связи: можно было бы конечно оставить так `$comments = Comment::where('film_id', '=', $film->id)->get();` но зачем? когда можно использовать связь, не думая о том какие там поля, условия и пр - ты так скрываешь логику получения комментов и пользуешься уже "готовыми" данными

2023-04-27 07:55 UTC, dmekhov commented on database/factories/UserFactory.php
> +            'role' => 'user',
Ага, поэтому я и написал что можно отложить ;)

2023-04-27 07:56 UTC, sokoloff-rv commented on app/Http/Controllers/CommentController.php
> +            $comments = Comment::where('film_id', '=', $filmId)->get();
Вот, теперь понял )

2023-04-27 07:58 UTC, dmekhov commented on routes/api.php
> +Route::get('/films/{film}/similar', [SimilarController::class, 'index']);
Забыл в этом контроллере (и в FavoriteController) поправить входящий параметр в методе.  

Не забудь потом исправить.

2023-04-27 07:59 UTC, sokoloff-rv commented on database/factories/UserFactory.php
> +            'role' => 'user',
Ну я уже перенес в константы. В принципе надо было сразу так сделать, так как по сути это ничего не меняет, а выглядит уже прилично.

2023-04-27 08:01 UTC, dmekhov commented
С форматом ответов еще надо будет повозиться, когда до тестов дойдешь - надо будет исправлять (сейчас лара отдает ошибки 404 и пагинированный ответ не совсем в том формате который ожидается по ТЗ)  
Сейчас не докапываюсь что бы не затягивать - т.к. в рамках этой задачи возвращение данных было не обязательно

2023-04-27 08:01 UTC, merged

2023-04-27 08:05 UTC, sokoloff-rv commented on routes/api.php
> +Route::get('/films/{film}/similar', [SimilarController::class, 'index']);
Ага, точно. Сейчас сразу исправлю в ветке следующего задания.